apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-backend
  namespace: default
  labels:
    app: insurance-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-backend
  template:
    metadata:
      labels:
        app: insurance-backend
    spec:
      containers:
        - name: backend
          # Replace galeyro with your real GitHub username in lowercase
          image: ghcr.io/galeyro/insurance-backend:v1.0.11 # {"$imagepolicy": "flux-system:insurance-backend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://my-postgres-postgresql:5432/insurance_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka:9092
            - name: KAFKA_USERNAME
              value: "user1"
            - name: KAFKA_PASSWORD
              value: "amIkM2sFfr"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-frontend
  namespace: default
  labels:
    app: insurance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-frontend
  template:
    metadata:
      labels:
        app: insurance-frontend
    spec:
      containers:
        - name: frontend
          # Replace galeyro with your real GitHub username in lowercase
          image: ghcr.io/galeyro/insurance-frontend:v1.0.8 # {"$imagepolicy": "flux-system:insurance-frontend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: default
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: ghcr.io/kafbat/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local-kraft
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: my-kafka:9092
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: PLAIN
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="amIkM2sFfr";
